# Client settings
host = "localhost:8080"
api_key = "your-api-key"

# Server settings
[server]
port = ":8080"
database_dsn = "postgres://root:password@database:5432/chatatui?sslmode=disable"
message_history_limit = 50
room_list_limit = 100
